### ISSUE TITLE
yt-dlp  upload issue

### ISSUE THREAD

**Issue by amitsha1** [SUHAIB-RASHID-DAR/Bulk-Text-uploader#1]
not downloading by a txt file that contain yt-dlp supported links

**Comment by SUHAIB-RASHID-DAR** [comment]
> not downloading by a txt file that contain yt-dlp supported links

what kinda links do you tried to download

**Comment by SUHAIB-RASHID-DAR** [comment]
> not downloading by a txt file that contain yt-dlp supported links

Fixed now

**Comment by ak-47-brar** [comment]
not working bro
